### ISSUE TITLE
Timeout of `npm start`?

### ISSUE THREAD

**Issue by michielbdejong** [ambanum/OpenTermsArchive#210]
Hi!

We're now running this code (without scheduler) on https://tosback.org (went live today!) and one thing we had to change was to add a timeout, so the process exits after one hour.

Did you have a similar experience or does `npm start` neatly exit after it reaches the last service in the alphabet?

**Comment by Ndpnt** [comment]
Hi!

It's a super good news to know that you use CGUs for ToSBack! 🎉

Regarding your exit issue, we do not have the same here. `npm start` properly exits after it reaches the last service. It's very curious… 🤔

**Comment by martinratinaud** [comment]
@michielbdejong I'm curious to see if you're still using this code and if it is still the same problem on our latest version

**Comment by michielbdejong** [comment]
Hi! Good question, truth is, I don't know! :) I haven't worked on ToS;DR for a while now, so will have to pass this question on to Justin Back:

@JustinBack I see that https://github.com/tosdr/tosback-crawler was last updated in February, are we still using it in production? If not, what are we using instead?

**Comment by JustinBack** [comment]
The timeout is causing issues with the crawler (the process gets killed during the git tasks and leaves a lockfile in place, preventing commits to the repositories) Removing that timeout gets the process stuck.

**Comment by martinratinaud** [comment]
Ok, @JustinBack i used to have this problem too but it seems it's ok now.
I've made many chances since I arrived (in february) and maybe you could try to re-sync ?

Please let me know if I can help.

**Comment by JustinBack** [comment]
Maybe @michielbdejong has the chance to as the fork has an entirely different commit history and a customized core which michiel worked on. I am not sure how [tosdr/tosback-crawler](https://github.com/tosdr/tosback-crawler) is bridged with [tosdr/tosback3](https://github.com/tosdr/tosback3) and if its even compatible with the master branch of [ambanum/OpenTermsArchive](https://github.com/ambanum/OpenTermsArchive).



![image](https://user-images.githubusercontent.com/40178814/128517951-8548ac5d-572c-4db6-a6cf-000ea1a0c0c0.png)

**Comment by michielbdejong** [comment]
Hm indeed,  I tried to create a pull request to merge the upstream changes but GitHub refuses to even display what the merge conflicts would be:
https://github.com/tosdr/tosback-crawler/compare/master...ambanum:master?expand=1

I don't really have time to dig into this at the moment, sorry. But if someone else wants to have a go, I'll be available to answer questions!

**Comment by martinratinaud** [comment]
Not sure I can help on this so I will close

Please feel free to re-open
