### ISSUE TITLE
Add professional cloud providers

### ISSUE THREAD

**Issue by LVerneyPEReN** [ambanum/OpenTermsArchive#261]
Hi,

It would be useful to have professionnal cloud providers into the list of services:

- [x] AWS : https://aws.amazon.com/fr/legal/
- [x] Scaleway : https://www.scaleway.com/fr/contrats/
- [x] OVH : https://www.ovh.com/fr/support/contrats/
- [ ] Azure
- [x] Google Cloud Platform

**Comment by clementbiron** [comment]
AWS added https://github.com/ambanum/OpenTermsArchive/commit/bfdf6ef166614cf2c2a5706c8cf9d19c74396c60 ✔️

**Comment by clementbiron** [comment]
Scaleway added https://github.com/ambanum/OpenTermsArchive/commit/681b2e11aab58c35e9e0a82209284319068b4e7c

**Comment by clementbiron** [comment]
OVHcloud added https://github.com/ambanum/OpenTermsArchive/commit/6d4920da4b474eadbcd882482cdd673e47bebc8b

**Comment by clementbiron** [comment]
Google Cloud Platform added https://github.com/ambanum/OpenTermsArchive/commit/2db235e78ebcb629d95e6c6deafbf93c54982b78

**Comment by clementbiron** [comment]
Azure documents are the same as Microsoft which are already tracked.
