### ISSUE TITLE
Documents dealing with special conditions related to covid

### ISSUE THREAD

**Issue by clementbiron** [ambanum/OpenTermsArchive#269]
GDI wants to add the following document : https://help.adroll.com/hc/en-us/articles/360042675351-Restricted-Content-and-Practices-COVID-19

I can't determine the exact type, it's looks like an `Ad Publishing Policy` document, but linked to the special conditions of COVID 19.

Adding the type `Ad Publishing Policy for COVID 19` sound the simplest solution. 

- Has anyone seen any other documents that deal with the specifics of covid 19?
- Do you have a cleaner solution?

**Comment by MattiSG** [comment]
Thank you for sharing this case example!

I believe this is a case for multi-pages documents, just like community guidelines on Twitter or Facebook. Indeed, AdRoll's “Restricted Content and Practices” spans multiple pages. This one dedicated to COVID-19 is just one example, there are many others.

> Has anyone seen any other documents that deal with the specifics of covid 19?

No.

As frustrating as it is, **I am in favour of explaining that it is currently not possible to track such documents at the moment**. The alternative is to take on debt by breaking the triptych declaration system, having the documents types grow out of control, and committing to merge at some later stage all these documents types.

I will give more details on `Ad Publishing Policy` in a separate issue.

**Comment by clementbiron** [comment]
> As frustrating as it is, I am in favour of explaining that it is currently not possible to track such documents at the moment. The alternative is to take on debt by breaking the triptych declaration system, having the documents types grow out of control, and committing to merge at some later stage all these documents types.

Agree with that 👍
