### ISSUE TITLE
Add Ad Publishing Privacy Policy type

### ISSUE THREAD

**Issue by clementbiron** [ambanum/OpenTermsArchive#270]
I can't detemine the type of this document : https://privacy.acuityads.com/technology-privacy-policy.html

Should we have to add `Ad Publishing Privacy Policy` to available types ?

**Comment by clementbiron** [comment]
Looks the same type for https://simpli.fi/simpli-fi-services-privacy-policy/

**Comment by clementbiron** [comment]
maybe more precise `Advertising Technology Privacy Policy`

**Comment by MattiSG** [comment]
I understand that AcuityAds is a service that aims at delivering ads. There is thus nothing specific to “Ad Publishing”: it is AcuityAd's business just like Google Search’s service aims at delivering search results. We should not create document types that describe provided services 🙂

The linked document states:

> This privacy policy outlines what information we collect, how we secure it, and how we use it in relation to the service AcuityAds provides to its customers via our advertising technology platform.

Thus, it describes how the _service provider_ commits on _personal data_ of the “data subjects”, i.e. visitors of website that use AcuityAds’ service. I would thus consider this document to be a `Data Controller Agreement`, describing to their end users (marketers) how they are handling personal data. Even though the wording is very declarative and could as well be read by visitors of the websites on which AcuityAds’ service is deployed, if we were to use a type such as `Trackers Policy`, this would mean this document applied to end users _of AcuityAds_, which is not the case.

Indeed, this document should not be confused with how the _service provider_ commits on _personal data_ of its _end users_ (i.e. advertisers), which would be a `Privacy Policy` and is available at https://privacy.acuityads.com/corporate-privacy-policy.html.

**Comment by MattiSG** [comment]
Let me correct what I wrote earlier: if really it is systematic for ad services to describe to tracked data subjects how their personal data is collected and handled, directly by the service provider to the data subject, and not to the end user of the service, then maybe indeed this warrants creating a new type.

The triptych would be:

```json
  "commitment": {
      "writer": "service provider",
      "audience": "data subject",
      "object": "data subject‘s personal data collection and handling"
    }
```

In order to find a good name, it would be useful to collect a list of such documents' names. So far, we have:

- “Technology Privacy Policy” for AcuityAds.
- “Advertising Service Policy” for TeAds.
- (I cannot access simpli.fi’s website)

Any other examples? 🙂

**Comment by clementbiron** [comment]
@AaronjSugarman maybe you can help us 🤟

In your opinion, should we use tye  `Data Controller Agreement` type for the following documents ?
- https://privacy.acuityads.com/technology-privacy-policy.html
- https://simpli.fi/simpli-fi-services-privacy-policy/
- https://www.teads.com/privacy-policy/

Or elsen we can add a new document type, i quote Matti :
> if really it is systematic for ad services to describe to tracked data subjects how their personal data is collected and handled, directly by the service provider to the data subject, and not to the end user of the service, then maybe indeed this warrants creating a new type.

Do you have any other exemple of ad services who describes their tracked data in this way ?

**Comment by AaronjSugarman** [comment]
> @AaronjSugarman maybe you can help us 🤟
> 
> In your opinion, should we use tye `Data Controller Agreement` type for the following documents ?
> 
> * https://privacy.acuityads.com/technology-privacy-policy.html
> * https://simpli.fi/simpli-fi-services-privacy-policy/
> * https://www.teads.com/privacy-policy/
> 
> Or elsen we can add a new document type, i quote Matti :
> 
> > if really it is systematic for ad services to describe to tracked data subjects how their personal data is collected and handled, directly by the service provider to the data subject, and not to the end user of the service, then maybe indeed this warrants creating a new type.
> 
> Do you have any other exemple of ad services who describes their tracked data in this way ?

I am most familiar with the ad publisher policies and not their privacy policies, but I have found that it is not uncommon for ad companies to have privacy policies to describe the data of tracked users. From brief research, here's one by Google Some brief research found this document from Google: https://policies.google.com/privacy?hl=en-US . I think creating a new type could be useful to describe this, because I don't believe these policies are addressing an end user's data (marketers), but rather the people being tracked by the ad platforms to deliver ads.

**Comment by clementbiron** [comment]
So let's add a new type ! 

We need to find a name, I complete the list of @MattiSG  

- “Technology Privacy Policy” for AcuityAds.
-  “Advertising Service Policy” for TeAds.
- "Services Privacy Policy" for Simpli.fi

I suggest to use "Advertising Service Policy" wich look the most relevant.

What do you think ?

**Comment by MattiSG** [comment]
I am not in favour of using the word “service” in document types, as it could probably be added everywhere 😉

What about:

```json
  "Tracker Provider Policy": {
    "commitment": {
      "writer": "service provider",
      "audience": "data subject",
      "object": "all tracking technologies made available to users and targeting their own users as data subjects"
    }
  },
```

?

**Comment by AaronjSugarman** [comment]
I put this response in another thread, but thought it might be useful here too @clementbiron 
"Emanuele: Reading through sounds like they be missing the point that there are 2 distinct ad policies
-The "ad policy", regulating the content inside the ad.
-The "publisher content policy" regulating the content around the ad.
All of the "ad publisher policies" submitted are around #2.""

**Comment by MattiSG** [comment]
Following #984, this issue has been moved to https://github.com/OpenTermsArchive/terms-types/issues/10 🙂
