### ISSUE TITLE
New platforms and services to be added

### ISSUE THREAD

**Issue by trujilloelsa** [ambanum/OpenTermsArchive#271]
**Communication**

- [x] LinkedIn 
- [x] Twitter, on a seulement les developer terms
- [x] Wire
- [x] Olvid
- [x] Zoom
- [x] Jitsi Meet
- [x] Teams (cf privacy policy, Microsoft)
- [x] ProtonMail
- [x] Nextdoor

**Search** 
- [X] Qwant
- [ ] Baidu

**Data analysis**
- [x] Palantir

**Ads**
- [x] ironSource
- [x] The Trade Desk

**Cloud**
- [x] OVHcloud
- [ ] Amazon Web Services
- [x] Scaleway

**Transportation**
- [ ] Uber
- [x] Lyft
- [x] Taxify

**Food** 
- [x] Deliveroo
- [ ] Uber Eats
- [x] Just Eat
- [x] Instacart

**Crypto**
- [x] Binance
- [ ] Coinbase
- [x] Kraken
- [ ] Robinhood

**Leisure**
- [ ] Apple Music
- [ ] Deezer (in French only)
- [ ] Shorts (YouTube)

**Dating**
- [x] Tinder
- [x] Bumble
- [x] Happn

**Comment by clementbiron** [comment]
Thanks !

**Comment by clementbiron** [comment]
- [x] Qwant  https://github.com/ambanum/OpenTermsArchive/commit/069f6f22a3062b23487de20286d26fc4d6a3ed71

**Comment by martinratinaud** [comment]
@clementbiron maybe we should create one issue per service, it would be easier to track WDYT ?

**Comment by martinratinaud** [comment]
in fact I put at least some checkboxes which I find easier to read

**Comment by martinratinaud** [comment]
@clementbiron I think until we know exactly what services we will be responsible for maintaining, we should not go on further we this and close.

What do you think?

**Comment by clementbiron** [comment]
ok for me

**Comment by MattiSG** [comment]
> until we know exactly what services we will be responsible for maintaining, we should not go on further we this and close

Indeed 😉
