### ISSUE TITLE
Remove Ad Publishing Policy document type

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#272]
I don't believe `Ad Publishing Policy` is a proper type.

It was added in #264, apparently to support adding Google's Adsense “acceptable use for publishers” (in #262), i.e. [this document](https://support.google.com/adsense/answer/9335564).

However, [the triptych](https://github.com/ambanum/OpenTermsArchive/blob/master/src/app/types.json#L177-L182) for `Ad Publishing Policy` is exactly the same as the one for [`Acceptable Use Policy`](https://github.com/ambanum/OpenTermsArchive/blob/master/src/app/types.json#L51-L57). These triptychs are exactly there to prevent duplication across similar names.

If the service provider, in the case of Google Adsense as in #264, or Adroll in #269 , is a service whose aim is to _provide ads_, then the _service provider_ stating in a document how its _end users_ (ad buyers) are expected to have an _acceptable and unacceptable usage_ of the service, is declaring its `Acceptable Use Policy`.

I thus believe that:

1. `Ad Publishing Policy` should be removed as a valid type (or redefined so that its triptych makes clear what is so specific to this new type). All services using them should be updated to `Acceptable Use Policy` as long as they are ads publishers. A quick search did not make me suspect there would be other services using that document type.
2. The document declared in #262 should be moved to a new service, Google AdSense. Indeed, Google Ads and Google AdSense are [two separate services targeting different users](https://www.ppchero.com/google-ads-vs-adsense-whats-the-difference/).
3. Associated documents’ history should be migrated.
4. [Indentation](https://github.com/ambanum/OpenTermsArchive/blob/master/src/app/types.json#L182-L184) should be fixed in `types.json` 😉

**Comment by clementbiron** [comment]
> Ad Publishing Policy should be removed as a valid type (or redefined so that its triptych makes clear what is so specific to this new type). All services using them should be updated to Acceptable Use Policy as long as they are ads publishers. A quick search did not make me suspect there would be other services using that document type.

I agree with that, I can handle it.

> The document declared in Update Google Ads.json #262 should be moved to a new service, Google AdSense. Indeed, Google Ads and Google AdSense are two separate services targeting different users.

Idem.

> Associated documents’ history should be migrated.

I'm not able to do it. Do you want @MattiSG to take care of it or should I ask @martinratinaud ? 

> Indentation should be fixed in types.json 😉

Yes ! 👌

@AaronjSugarman being as the origin of the pull request #262, please read this discussion. Your opinion could be important and I would prefer to wait for your answer before going ahead.

Thank you Matti for this feedback

**Comment by AaronjSugarman** [comment]
> > Ad Publishing Policy should be removed as a valid type (or redefined so that its triptych makes clear what is so specific to this new type). All services using them should be updated to Acceptable Use Policy as long as they are ads publishers. A quick search did not make me suspect there would be other services using that document type.
> 
> I agree with that, I can handle it.
> 
> > The document declared in Update Google Ads.json #262 should be moved to a new service, Google AdSense. Indeed, Google Ads and Google AdSense are two separate services targeting different users.
> 
> Idem.
> 
> > Associated documents’ history should be migrated.
> 
> I'm not able to do it. Do you want @MattiSG to take care of it or should I ask @martinratinaud ?
> 
> > Indentation should be fixed in types.json 😉
> 
> Yes ! 👌
> 
> @AaronjSugarman being as the origin of the pull request #262, please read this discussion. Your opinion could be important and I would prefer to wait for your answer before going ahead.
> 
> Thank you Matti for this feedback
I agree that an "Ad Publisher Policy" is specific type of "Acceptable Use Policy", and thus can be replaced by "Acceptable Use Policy" to simplify things. My only concern and argument in favor of keeping "Ad Publisher Policy" is that it would make it easier to identify which of the Acceptable Use Policies cover ad publishing (i.e. the majority of documents I emailed asking Open Terms Archive to track from GDI). For example, due to my work I'm familiar with which Acceptable Use Policies concern ads by name alone, but I do not believe that to be the case for most audiences. I will ultimately leave it up to your discretion @clementbiron since you know more about the organization of the Open Terms Archive. I hope this feedback was helpful!

**Comment by MattiSG** [comment]
Thank you @AaronjSugarman for your quick reply!

I agree that it would be useful to add some _categories_ to service providers, so that we know that the `Acceptable Use Policy` for an ad provider is about ads. Right now, that information has to be stored in an independent database outside from OTA.
However, I am not sure we can have a definite ontology for these categories though (i.e. they might not always be exclusive and might be more like tags, or some services might be too hard to classify). Such a system would need a lot more thought.

> Do you want @MattiSG to take care of it

No, I'm not familiar enough with that process, sorry 🙁

**Comment by clementbiron** [comment]
@martinratinaud could you please migrate the history of documents with the `Ad Publishing Policy type` to `Acceptable Use Policy` ?

Full rewrite history documentation [is here](https://github.com/ambanum/OpenTermsArchive/blob/master/scripts/rewrite/README.md) and there is a [detailed explanation for document type renaming](https://github.com/ambanum/OpenTermsArchive/blob/master/scripts/rewrite/README.md#document-type).

**Comment by martinratinaud** [comment]
Hi @MattiSG 

I've tried to rewrite the history but I guess that 1,000,000 commits may be very large to process and will lead to problems.
I will keep trying but with my little knowledge of all this part and the information that it took almost a week to process last time it was done in december, i believe this is not the right way to go for now.

So three options here
1. leave the document type as is if we consider it not important
2. get support from @Ndpnt to see if it's possible to bypass this limitation with a hack or a slightly different approach
3. initiate the big refactoring we've been discussing

I believe 2. could be done to make sure there is definitely not an easy fix but I think we should more focus on getting funded and tackle the whole refactoring alltogether

What do you think ?

**Comment by MattiSG** [comment]
I believe you have a better understanding of the value of the accumulated history for these documents 🙂 I don't believe it is a big problem to leave these commits behind, it is just lost information.

So I would be in support of another option: just migrate all document types, and abandon the history.

**Comment by clementbiron** [comment]
I suggest to abandon the history, it seems to me simpler and will allow to start from better bases.  

@AaronjSugarma as you are the main person involved in the following of this type of document, does this seem like a feasible option to you ?

**Comment by AaronjSugarman** [comment]
> I suggest to abandon the history, it seems to me simpler and will allow to start from better bases.
> 
> @AaronjSugarma as you are the main person involved in the following of this type of document, does this seem like a feasible option to you ?

@clementbiron Would this mean removing all documents that have been classified as an ad publishing policy? I believe that I re-added all the relevant GDI documents through the website link and classified them as Terms Of Service, so that should be fine!

**Comment by clementbiron** [comment]
@AaronjSugarman It's mean that the history of the documents with the type `Ad Publishing Policy` will be loose. In other words, it's like we will start now to follow this documents.

It's better thant ever, what do you think ?

**Comment by AaronjSugarman** [comment]
@clementbiron I want to point out something Emanuele told me when I showed him this thread:
"Emanuele: Reading through sounds like they be missing the point that there are 2 distinct ad policies
-The "ad policy", regulating the content inside the ad.
-The "publisher content policy" regulating the content around the ad.
All of the "ad publisher policies" submitted are around #2."

**Comment by MattiSG** [comment]
Following #984, this issue has been moved to https://github.com/OpenTermsArchive/terms-types/issues/9 🙂
