### ISSUE TITLE
National Geographic - choose the right ToS

### ISSUE THREAD

**Issue by clementbiron** [ambanum/OpenTermsArchive#274]
I need help to choose the right ToS for https://www.nationalgeographic.com/

The new ToS fetch url is https://disneytermsofuse.com/english/, witch is the english version of the document for USA.

https://disneytermsofuse.com gives us the possibility to choose ToS for many languages and many country, unfortunately their is no ToS in english language for a EU country. 

So, what we sould prefer do now ?
- choose a European based ToS event though it's not in english
- choose a english based ToS event though it does not deal with European law

@MattiSG @martinratinaud @Ndpnt What is your point of view?

**Comment by MattiSG** [comment]
I believe this decision lies with the entity that wants to track that service 🙂

From my point of view, I would favour English speaking to increase consistency, as it is likely that some other documents that are already tracked are already in a jurisdiction other than EU, so let’s at least minimise language inconsistency.

**Comment by clementbiron** [comment]
> I believe this decision lies with the entity that wants to track that service 🙂 

I do not recall that the addition of this document was made at the request of anyone. 

> From my point of view, I would favour English speaking to increase consistency, as it is likely that some other documents that are already tracked are already in a jurisdiction other than EU, so let’s at least minimise language inconsistency.

I agree with you, let's choosing English based document.

**Comment by clementbiron** [comment]
done https://github.com/ambanum/OpenTermsArchive/commit/9099a12a8fa73d0bf32895a742b4e9f4d4a51b33

**Comment by MattiSG** [comment]
> I do not recall that the addition of this document was made at the request of anyone.

Then it is certainly a remnant from ToSBack's archive 🙂
