### ISSUE TITLE
Shockwave.com blinks

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#275]
I receive change notifications for Shockwave.com Trackers Policy and Privacy Policy every hour, which I think is more likely related to an issue with noise removal rather than with that regular changes in the documents themselves 😉

Problem comes from one link that is changing everytime (See https://github.com/ambanum/OpenTermsArchive-versions/commit/7c4682e19c3?utm_source=sendinblue&utm_campaign=CGUs_Document_update&utm_medium=email)

We can
- remove the link
- add a custom rule as this may often appear

**Comment by martinratinaud** [comment]
I discovered it's the same for ValueImpression with the same pattern

https://github.com/ambanum/OpenTermsArchive-versions/commit/8b7c39fbb22?utm_source=sendinblue&utm_campaign=CGUs_Document_update&utm_medium=email

**Comment by clementbiron** [comment]
It's look like CloudFare email obfuscation : https://stackoverflow.com/questions/44418721/ive-seen-this-email-protection-on-a-website-and-would-like-to-know-how-they-hav

**Comment by martinratinaud** [comment]
Yes I added a cleanup before screenshot function as we have that on many
accounts

Should be fixed and deployed now

**Comment by martinratinaud** [comment]
Not receiving blinking documents anymore :-)
