### ISSUE TITLE
Improve the website privacy policy

### ISSUE THREAD

**Issue by rgrunbla** [ambanum/OpenTermsArchive#278]
Hello,

Given the website collects email addresses (which are PIIs), it would be nice to have a better privacy policy at https://www.opentermsarchive.org/en/privacy-policy, for example with information on how to access, restrict, modify such data.

Right now, the https://www.opentermsarchive.org/en/privacy-policy is pretty much empty.

**Comment by martinratinaud** [comment]
Thanks for the insight, you're right and we'll update that.

FYI though, we do not store your email now, you're just contributing by sending us an email but our goal is to create an issue/PR in github directly instead of this.

BTW would you be interested in contributing directly via PRs issues if I developed this functionnality ?
and if yes, would you login with your github account to do so ?

Thanks

**Comment by rgrunbla** [comment]
Hello,

> FYI though, we do not store your email now, you're just contributing by sending us an email but our goal is to create an issue/PR in github directly instead of this.

To be clear, I'm talking about the form to fulfill in order to receive updates to terms of service: 

<img src="https://user-images.githubusercontent.com/42433779/127832843-d37d16a6-c55f-49dd-ba1d-e88da8694756.png" width="400" />

If you're not storing emails, I'm afraid this form is mostly useless ;)

**Comment by martinratinaud** [comment]
Acttually we are storing emails in SendInBlue but not on our side, so I'm not sure :-)

**Comment by martinratinaud** [comment]
Anyway we need to check this.

In the meantime, as we may collect emails when a contributor is adding a service, we also could add the following

```
When submitting a contribution to Open Terms Archive, you will be asked to send an email to contact@opentermsarchive.org.You will then receive an email from us, if your submission has been approved.These emails will be used for contribution purposes only.We do not use your email address for other purposes.Furthermore, you may subscribe by email to be notified whenever a change is registered on the contractual document of your choice. You may then unsubscribe easily. Your email address will then be erased from our mailing list.

Pour contribuer à Open Terms Archive, il vous sera demandé d’envoyer un email, après avoir rempli un court formulaire, à l’adresse contact@opentermsarchive.org.Vous recevrez par la suite un mail de notre part, si votre proposition d’ajout de document a été validée.Ces emails seront seulement utilisés à des fins de contribution. Ils ne seront en aucun cas utilisés à des fins marketing. Par ailleurs, vous avez la possibilité de vous abonner par mail pour être notifié dès lors qu’un changement survient sur le document contractuel de votre choix.Vous pouvez vous désabonner facilement de ces envois.Votre adresse ne fera dès lors plus partie de notre liste de diffusion.
```

Thanks to @trujilloelsa for the text

**Comment by MattiSG** [comment]
> Actually we are storing emails in SendInBlue but not on our side, so I'm not sure

SendInBlue acts as a data processor, but you are very much responsible for their handling as the data controller 🙂 It is your privacy policy that applies. And right now, it is indeed missing email handling elements.

**Comment by MattiSG** [comment]
@martinratinaud is the text you mentioned in https://github.com/ambanum/OpenTermsArchive/issues/278#issuecomment-891968291 still relevant since you seem to now create issues (cf. #310, #311, #312) rather than sending an email through the contribution tool?

**Comment by clementbiron** [comment]
Hello @rgrunbla 

I have just completed the Open Terms Archive website privacy policy : https://opentermsarchive.org/en/privacy-policy

Thanks for opening this issue.
