### ISSUE TITLE
Page preview broken on GraphCMS's policies

### ISSUE THREAD

**Issue by tcmb** [ambanum/OpenTermsArchive#279]
When trying to add the ToS and PP of GraphCMS, the graphic assets of the original page are overlaid in huge sizes over the preview where i should mark the relevant parts, making it impossible to select anything.

When trying to select these elements for removal, in one case a 404 error appeared, in another case the document preview was replaced by opentermsarchive's homepage.

URLs I tried to add:

- https://graphcms.com/terms
- https://graphcms.com/privacy

**Comment by tcmb** [comment]
This is what it looked like for me:
![Screenshot 2021-07-30 152902](https://user-images.githubusercontent.com/1877592/127661411-1a5149cf-cb63-4c6e-99c0-4543f2ba258a.png)
![Screenshot 2021-07-30 152928](https://user-images.githubusercontent.com/1877592/127661423-619ad949-0018-4b63-b4f9-38a3bdc2a475.png)

**Comment by martinratinaud** [comment]
Hi @tcmb and thanks for the feedback,
I will check what's wrong with it soon

**Comment by martinratinaud** [comment]
@tcmb thanks for the heads up, I just released a patch that should be deployed in 5 min

We would be very glad to have you on board as a contributor and here is the [Contributing guide](https://github.com/ambanum/OpenTermsArchive/blob/master/CONTRIBUTING.md)

I'm also available anytime if you have any questions
