### ISSUE TITLE
Add "Terms of Service" of "Ricardo"

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#282]
Addition requested through https://www.opentermsarchive.org/en/contribute

https://www.opentermsarchive.org/en/contribute/service?documentType=Terms%20of%20Service&name=Ricardo&selectedCss[]=.article-body&step=2&url=https%3A%2F%2Fhelp.ricardo.ch%2Fhc%2Fde%2Farticles%2F115002934305-AGB-und-Reglemente&expertMode=true

**Comment by clementbiron** [comment]
The document requested in addition is in Deutsh and not available in English.

In order to maintain good data quality we currently only follow documents in English.
