### ISSUE TITLE
Add "Terms of Service" of "Swiss Post"

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#283]
Addition requested through https://www.opentermsarchive.org/en/contribute

https://www.opentermsarchive.org/en/contribute/service?documentType=Terms%20of%20Service&name=Swiss%20Post&selectedCss[]=%23main&step=2&url=https%3A%2F%2Fwww.post.ch%2Fde%2Fpages%2Ffooter%2Fallgemeine-geschaeftsbedingungen-agb&expertMode=true

**Comment by clementbiron** [comment]
The addition requested is about a page that lists a set of documents, not a page dedicated to one type of document.

And documents have to be in english (i easily found this page https://www.post.ch/en/pages/footer/general-terms-and-conditions-gtc).
