### ISSUE TITLE
Add "Privacy Policy" of "Swiss Post"

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#284]
Addition requested through https://www.opentermsarchive.org/en/contribute

https://www.opentermsarchive.org/en/contribute/service?documentType=Privacy%20Policy&name=Swiss%20Post&selectedCss[]=%23main&step=2&url=https%3A%2F%2Fwww.post.ch%2Fde%2Fpages%2Ffooter%2Fdatenschutz-und-rechtliches&expertMode=true

**Comment by clementbiron** [comment]
Done https://github.com/ambanum/OpenTermsArchive/commit/fa49973a5b10a8f9062d6550cc0331cf2dbec0ac
