### ISSUE TITLE
Add "Terms of Service" of "Energia (Ireland)"

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#287]
Addition requested through https://www.opentermsarchive.org/en/contribute

https://www.opentermsarchive.org/en/contribute/service?documentType=Terms%20of%20Service&name=Energia%20%28Ireland%29&removedCss[]=.header&removedCss[]=.jumbotron-content&removedCss[]=.privacy-menu%3Anth-child%281%29&removedCss[]=.footer-social-linkedin%20%3E%20svg&selectedCss[]=.privacy-offset&step=2&url=https%3A%2F%2Fwww.energia.ie%2Fprivacy%2Fsmart-terms-conditions&expertMode=true

**Comment by clementbiron** [comment]
Done https://github.com/ambanum/OpenTermsArchive/commit/b0465b304203e37c35851e09a5655d1bba87531c
