### ISSUE TITLE
Add "Terms of Service" of "OnlyFans"

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#292]
Addition requested through https://www.opentermsarchive.org/en/contribute

https://www.opentermsarchive.org/en/contribute/service?documentType=Terms%20of%20Service&expertMode=true&name=OnlyFans&selectedCss[]=.b-static-content&step=2&url=https%3A%2F%2Fonlyfans.com%2Fterms&expertMode=true

**Comment by martinratinaud** [comment]
@MattiSG Need some help on this

Here is all that is listed in this document

Terms of Use for all Users
Terms of Use for Fans
Terms of Use for Creators
Acceptable Use Policy
Referral Program Terms
Complaints Policy
Platform to Business Regulation Terms

My idea would be to have

Privacy Policy
- Terms of Use for all Users
- Terms of Use for Fans
- Terms of Use for Creators

Acceptable Use Policy
- Acceptable Use Policy

First, 

- [ ] do you agree?
- [ ] what about the other type of files?

Thanks

**Comment by MattiSG** [comment]
### Terms of Use for Fans

I don't understand why the Terms of Use should have the type “Privacy Policy” 🤔

From what I read, the Terms of Use for all Users and the Terms of Use for Fans describe how the _service provider_ intends its _end users_ to have the _service usage_.

The matching triptych is:
```json
      "writer": "service provider",
      "audience": "end user",
      "object": "end user’s service usage"
```

…thus the matching document type is `Terms of Use`.

### Terms of Use for Creators

The Terms of Use for all Users and the Terms of Use for Creators describe how the _service provider_ intends its content creators, i.e. more generally _business partners_ to have the _service usage_ in a commercial way.

The matching triptych is:
```json
      "writer": "service provider",
      "audience": "content creators" / "business partners",
      "object": "commercial service usage"
```

…thus the best matching document type is `Commercial Terms`.

I find an ambiguity in the definition of Commercial Terms: it could either describe how business partners use the service, or it could be guidelines for reselling the service. Looking at some defined documents (Facebook and Google), it seems the former acception is currently used. I'm thus in favour of:

1. Adding the document with the parts “Terms of Use for all Users”, “Terms of Use for Creators” and “Platform to Business Regulation Terms” (explicitly mentioned as also applicable to Creators in the EU and UK, so should be tracked in the EU jurisdiction) as `Commercial Terms`.
2.  Changing the triptych from `audience: commercial intermediaries`  to `audience: commercial partners, content creators in a platform` to disambiguate the current usage.

### Acceptable Use Policy

`Acceptable Use Policy` obviously :wink:

### Referral Program Terms

I'd add this one to both `Terms of Use` and `Commercial Terms`. Indeed:

> These Referral Program Terms are additional terms which apply if you use the OnlyFans Referral Program. These Referral Program Terms form part of your agreement with us.

### Complaints Policy

We could add this one to both `Terms of Use` and `Commercial Terms`. Indeed:

> If you are a User of OnlyFans, this Complaints Policy forms part of your agreement with us.

However, this one is a bit tricky as it also applies to non-users. A random passer-by might file a complaint without the service. In my view, this is a new triptych and it would thus be worth creating a new document type:

```json
  "Complaints Policy": {
    "commitment": {
      "writer": "service provider",
      "audience": "anyone",
      "object": "how generic complaints will be handled"
    }
  }
```

I would also update the `Copyright Claims Policy` accordingly, changing `audience: end user` to `audience: anyone`, and `object: copyright complaints (DMCA…)` to `object: how copyright complaints (DMCA…) will be handled`. This one might end up being integrated into the Complaints Policy if we encounter services whose terms handle the Copyright Claims as part of a more generic Complaints Policy.

## Recap

In my view, we'd have the following todo:

- [ ] `Terms of Use `: `Terms of Use for all Users` +  `Terms of Use for Fans` + `Referral Program Terms`
- [ ] `Commercial Terms`: `Terms of Use for all Users` +  `Terms of Use for Creators` + `Referral Program Terms` + `Platform to Business Regulation Terms`
- [ ] `Acceptable Use Policy`: `Acceptable Use Policy`
- [ ] `Complaints Policy`: `Complaints Policy`
- [ ] Update `Commercial Terms` definition.
- [ ] Update `Copyright Claims Policy` definition.

**Comment by martinratinaud** [comment]
Deployed
