### ISSUE TITLE
Add "Terms of Service" of "Cloudflare"

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#293]
Addition requested through https://www.opentermsarchive.org/en/contribute

https://www.opentermsarchive.org/en/contribute/service?documentType=Terms%20of%20Service&name=Cloudflare&selectedCss[]=.col-lg-8%20%3E%20.rich-text-renderer&step=2&url=https%3A%2F%2Fwww.cloudflare.com%2Fterms%2F&expertMode=true

**Comment by martinratinaud** [comment]
Here is the corresponding json

```
{
  "name": "Cloudflare",
  "documents": {
    "Terms of Service": {
      "fetch": "https://www.cloudflare.com/terms/",
      "select": [
        ".col-lg-8 > .rich-text-renderer"
      ]
    }
  }
}
```

@MattiSG can you please assist me on telling what document type it is: `Cloudflare Self-Serve Subscription Agreement`

**Comment by MattiSG** [comment]
This document seems to describe how the _service provider_ intends to handle the _end user’s usage_ of its self-serve subscription service, for the _end user_ to read. The matching triptych is:

```
      "writer": "service provider",
      "audience": "end user",
      "object": "end user’s service usage"
```

…which is `Terms of Service` 😉

“Self-Serve Subscription” seems to be one of two Cloudflare's offers, the other being the [Enterprise Subscription](https://www.cloudflare.com/fr-fr/enterpriseterms/).

The provided JSON thus should be edited to:

```json
{
  "name": "Cloudflare Self-Serve",
  "documents": {
    "Terms of Service": {
      "fetch": "https://www.cloudflare.com/terms/",
      "select": [
        ".col-lg-8 > .rich-text-renderer"
      ]
    }
  }
}
```

**Comment by martinratinaud** [comment]
And so @MattiSG the name of the file would be `Cloudflare.json` or `Cloudflare Self-Serve.json`.

My guess: still `Cloudflare.json`

**Comment by martinratinaud** [comment]
Just deployed
