### ISSUE TITLE
OkCupid terms are changing on every request

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#294]
I have been forced to remove OkCupid from the list because it has a behavior which I was not able to bypass

Here is the history of changes: https://github.com/ambanum/OpenTermsArchive-versions/commits/master/OkCupid/Privacy%20Policy.md

You can see that one time it adds the content, and the other one it removes it.

I've made a distinct branch on OpenTermsArchive-snapshots with the raw html code tidied so that changes are more obvious

https://github.com/ambanum/OpenTermsArchive-snapshots/compare/fix/okcupid

You can see that it oscillates between
- an iframe bing moved https://github.com/ambanum/OpenTermsArchive-snapshots/commit/2058a817c84d9962cf1c3600892c8e599ec279e9
- and moved back https://github.com/ambanum/OpenTermsArchive-snapshots/commit/a91c0b9a4daeef1ff88fe3045ad941c50e0cdbb1
- moved https://github.com/ambanum/OpenTermsArchive-snapshots/commit/84d269e565eeb7917ea87cb4d5e18c3dae1c6508
- and moved back https://github.com/ambanum/OpenTermsArchive-snapshots/commit/c5466a638c961fbdc85a9d90888393875b42343d
- and finally some content removed https://github.com/ambanum/OpenTermsArchive-snapshots/commit/6b874a73e8b56e31adc280d23132afe8d1e4fcc8

I have very little idea of how to handle this

@MattiSG @Ndpnt maybe you had already that kind of problems before ?

In the meantime, i will remove the service as it is creating too much clutter on the `versions` repo

**Comment by martinratinaud** [comment]
I created a branch `chore/debug-snapshots` to easily debug on local with prettified snapshots

**Comment by martinratinaud** [comment]
Maybe @xiaoyunyang from @okcupid can help us explain why the privacy policy page is changing from time to time.
That would be the best :-)

**Comment by MattiSG** [comment]
I have no idea why this happens, this seems to be specific to the service provider. I don't believe it is worth investing too much effort in it at that stage.

Just to make it explicit though: I believe it is important that the prettifier for snapshots is not deployed into production 🙂 Snapshots should not be edited in any way, this is an important invariant in the process, that enables us to improve filters a posteriori if needed 🙂

**Comment by martinratinaud** [comment]
@MattiSG I'm truly sorry but the prettifier for snapshots has been on production before I saw this comment :-(

Also I have a slightly different vision on this and especially for the things I removed from the snapshots like
- beacon number
- email-protection stuff
- nonce 

So I can remove it of course and pass it in post filters, but I firstly did this because of the number of snapshots taken which is growing insanely fast with the number of services added.
