### ISSUE TITLE
Add GraphCMS - Terms of Service

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#297]
test martin body

**Comment by martinratinaud** [comment]
new comment test

**Comment by martinratinaud** [comment]
new comment test

**Comment by martinratinaud** [comment]
Addition has been requested again through the contribution tool


New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
undefined

Or you can see the JSON generated here:
```json
undefined
```

You will need to create the following file in the root of the project: `services/GraphCMS.json`

**Comment by martinratinaud** [comment]
Addition has been requested again through the contribution tool


New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
undefined

Or you can see the JSON generated here:
```json
undefined
```

You will need to create the following file in the root of the project: `services/GraphCMS.json`

**Comment by martinratinaud** [comment]
Addition has been requested again through the contribution tool


You can see the work done by the awesome contributor here:
http://localhost:3000/en/contribute/service?documentType=Terms%20of%20Service&expertMode=true&name=GraphCMS&selectedCss[]=.py-12&step=2&url=https%3A%2F%2Fgraphcms.com%2Fterms&expertMode=true

Or you can see the JSON generated here:
```json
[object Object]
```

You will need to create the following file in the root of the project: `services/GraphCMS.json`

**Comment by MattiSG** [comment]
Hey! I'm getting many notifications because of these tests, along with 8 other watchers 🙂
Could you maybe use a fork of this repo when trying out the GitHub API? I tend to recommend this option to avoid impacting a “production” repo 🙂

**Comment by MattiSG** [comment]
(as a side note, I recommend to create a PR straight away —it's slightly more work with the GitHub API but does pay off for maintainers)

**Comment by martinratinaud** [comment]
@MattiSG sorry about that :-)
Noted for the PR but I will do this if I get enough contributions :-)

**Comment by martinratinaud** [comment]
Addition has been requested again through the contribution tool


You can see the work done by the awesome contributor here:
https://www.opentermsarchive.org/en/contribute/service?documentType=Terms%20of%20Service&name=GraphCMS&selectedCss[]=.py-12%20%3E%20.mx-auto&step=2&url=https%3A%2F%2Fgraphcms.com%2Fterms&expertMode=true&expertMode=true

Or you can see the JSON generated here:
```json
{
  "name": "GraphCMS",
  "documents": {
    "Terms of Service": {
      "fetch": "https://graphcms.com/terms",
      "select": [
        ".py-12 > .mx-auto"
      ]
    }
  }
}
```

You will need to create the following file in the root of the project: `services/GraphCMS.json`

**Comment by martinratinaud** [comment]
this was first a test issue, but can now be converted to a reall one !
