### ISSUE TITLE
Handle services that are under maintenance

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#301]
We can see here

https://github.com/ambanum/OpenTermsArchive-versions/commit/1943f0e5ac0

That new version has been emitted even though the service was under maintenance.

@clementbiron @MattiSG what do you think should happen ?

**Comment by MattiSG** [comment]
I'd say this is acceptable noise as long as it does not happen often.

In some future, we might manually curate these versions out from the database, to increase the quality of the dataset. I doubt a fully automated system would be welcome, as the risk of false positive could be high.

I suggest we keep track of such occasions in this issue, and reconvene on a solution when we accumulated at least 10 instances 🙂

**Comment by MattiSG** [comment]
I changed the tag as I don't believe this is a bug: the system works just as intended, it is just a bit noisy 🙂

**Comment by martinratinaud** [comment]
Thanks @MattiSG ,I think we should close it then as it would be even more noise :-)

**Comment by martinratinaud** [comment]
Closed then, feel free to reopen in case it happens again
