### ISSUE TITLE
Get back user's contact on contribution

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#302]
As we can see here https://github.com/ambanum/OpenTermsArchive/issues/300

A user has contributed but it seemed the entry was already in the database.

A problem with this new automatic creation of issues is that I do not ask for the user's email (as I did not want to put it directly inside the issue.

Any clever idea on how to handle this ?

If you want to test the workflow, you can try it on preprod.opentermsarchive.org and the issue will be created on https://github.com/ambanum/test-repo/issues

**Comment by MattiSG** [comment]
You could very well encrypt the email address with an asymmetric key, add the encrypted version to the payload and decrypt it manually when needed 🙂

In the specific example given, why is it a problem if the user cannot be informed that they wanted to add some service that was already tracked? Their intention was to add it, it is in the database, they should be happy 😉 
I believe this pushes more for adding a check that the current URL is not already in the database in the contribution tool than for storing email 🙂

**Comment by martinratinaud** [comment]
@MattiSG We do not store anything in a database for now, everything is in github

So either
- we write the user's email encrypted in the github issue, which seems a bit weird to me but would work
- we setup a database and store the email + the link to the issue

Let's go for the first one then I guess :-)

**Comment by MattiSG** [comment]
I was indeed suggesting the first option. 

It does not seem much weirder to me than opening an issue with a code block instead of a PR, and I’m not so certain of the use case, so that seems like an easy and fast way to get this feature 🙂

Will you add the private key to the shared keychain?

**Comment by martinratinaud** [comment]
@MattiSG I'm not so familiar with that
Do you have a library or article to recommend ?

Thanks

**Comment by martinratinaud** [comment]
Ok so what I will do instead is 
- after contribution, ask if the user wants to receive notifications when service will be on
- create a new list in SIB automatically

@clementbiron maybe a quick mockup could be nice

**Comment by MattiSG** [comment]
I will close this issue in this repo. If it is still up to date, please reopen in https://github.com/opentermsarchive/contribution-tool 🙂
