### ISSUE TITLE
Add Zoom Terms of Service - Terms of Service

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#303]
New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
https://opentermsarchive.org/en/contribute/service?documentType=Terms%20of%20Service&name=Zoom%20Terms%20of%20Service&removedCss[]=.li5%3Anth-child%288%29&selectedCss[]=.ol2%3Anth-child%285%29%20%3E%20.li5%3Anth-child%281%29%20%3E%20.s3&selectedCss[]=.ol2%20%3E%20.li5%3Anth-child%282%29%20%3E%20.s3&selectedCss[]=.li5%3Anth-child%283%29%20%3E%20.s3%3Anth-child%281%29&selectedCss[]=.ol2%20%3E%20.li5%3Anth-child%284%29%20%3E%20.s3&selectedCss[]=.li5%3Anth-child%289%29%20%3E%20.s3&selectedCss[]=.li5%3Anth-child%2810%29%20%3E%20.s3&selectedCss[]=.li5%3Anth-child%2811%29%20%3E%20.s3&selectedCss[]=.li5%3Anth-child%2812%29&selectedCss[]=.li5%3Anth-child%2815%29%20%3E%20.s3&selectedCss[]=.li5%3Anth-child%2817%29%20%3E%20.s3&selectedCss[]=.li5%3Anth-child%2819%29%20%3E%20.s3&selectedCss[]=.li5%3Anth-child%2821%29%20%3E%20.s3&step=2&url=https%3A%2F%2Fzoom.us%2Fterms&expertMode=true

Or you can see the JSON generated here:
```json
{
  "name": "Zoom Terms of Service",
  "documents": {
    "Terms of Service": {
      "fetch": "https://zoom.us/terms",
      "select": [
        ".ol2:nth-child(5) > .li5:nth-child(1) > .s3",
        ".ol2 > .li5:nth-child(2) > .s3",
        ".li5:nth-child(3) > .s3:nth-child(1)",
        ".ol2 > .li5:nth-child(4) > .s3",
        ".li5:nth-child(9) > .s3",
        ".li5:nth-child(10) > .s3",
        ".li5:nth-child(11) > .s3",
        ".li5:nth-child(12)",
        ".li5:nth-child(15) > .s3",
        ".li5:nth-child(17) > .s3",
        ".li5:nth-child(19) > .s3",
        ".li5:nth-child(21) > .s3"
      ],
      "remove": [
        ".li5:nth-child(8)"
      ]
    }
  }
}
```

You will need to create the following file in the root of the project: `services/Zoom Terms of Service.json`

**Comment by clementbiron** [comment]
Done 16058a578627647569d12e9abf2cefe0525a1237
