### ISSUE TITLE
Add Zoom - Privacy Policy

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#304]
New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
https://opentermsarchive.org/en/contribute/service?documentType=Privacy%20Policy&name=Zoom&selectedCss[]=ul%3Anth-child%287%29%20%3E%20li%3Anth-child%283%29&selectedCss[]=ul%3Anth-child%287%29%20%3E%20li%3Anth-child%285%29&selectedCss[]=ul%3Anth-child%287%29%20%3E%20li%3Anth-child%2810%29&selectedCss[]=ul%3Anth-child%287%29%20%3E%20li%3Anth-child%288%29&selectedCss[]=ul%3Anth-child%287%29%20%3E%20li%3Anth-child%289%29&selectedCss[]=ul%3Anth-child%2810%29&selectedCss[]=ul%3Anth-child%2814%29&selectedCss[]=ul%3Anth-child%2818%29%20%3E%20li%3Anth-child%281%29%20%3E%20ul&selectedCss[]=ul%3Anth-child%2818%29%20%3E%20li%3Anth-child%285%29%20%3E%20ul&selectedCss[]=ul%3Anth-child%2821%29&selectedCss[]=ul%3Anth-child%2846%29&selectedCss[]=ul%3Anth-child%2850%29&selectedCss[]=p%3Anth-child%2857%29&selectedCss[]=p%3Anth-child%2858%29&selectedCss[]=p%3Anth-child%2859%29&selectedCss[]=p%3Anth-child%2873%29&step=2&url=https%3A%2F%2Fzoom.us%2Fprivacy&expertMode=true

Or you can see the JSON generated here:
```json
{
  "name": "Zoom",
  "documents": {
    "Privacy Policy": {
      "fetch": "https://zoom.us/privacy",
      "select": [
        "ul:nth-child(7) > li:nth-child(3)",
        "ul:nth-child(7) > li:nth-child(5)",
        "ul:nth-child(7) > li:nth-child(10)",
        "ul:nth-child(7) > li:nth-child(8)",
        "ul:nth-child(7) > li:nth-child(9)",
        "ul:nth-child(10)",
        "ul:nth-child(14)",
        "ul:nth-child(18) > li:nth-child(1) > ul",
        "ul:nth-child(18) > li:nth-child(5) > ul",
        "ul:nth-child(21)",
        "ul:nth-child(46)",
        "ul:nth-child(50)",
        "p:nth-child(57)",
        "p:nth-child(58)",
        "p:nth-child(59)",
        "p:nth-child(73)"
      ]
    }
  }
}
```

You will need to create the following file in the root of the project: `services/Zoom.json`

**Comment by clementbiron** [comment]
Done 16058a578627647569d12e9abf2cefe0525a1237
