### ISSUE TITLE
Add Scalingo - Terms of Service

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#307]
New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
https://opentermsarchive.org/en/contribute/service?documentType=Terms%20of%20Service&name=Scalingo&selectedCss[]=.mx-sm-auto&selectedCss[]=.title&step=2&url=https%3A%2F%2Fscalingo.com%2Fterms-of-service&expertMode=true

Or you can see the JSON generated here:
```json
{
  "name": "Scalingo",
  "documents": {
    "Terms of Service": {
      "fetch": "https://scalingo.com/terms-of-service",
      "select": [
        ".mx-sm-auto",
        ".title"
      ]
    }
  }
}
```

You will need to create the following file in the root of the project: `services/Scalingo.json`

**Comment by clementbiron** [comment]
See https://github.com/ambanum/OpenTermsArchive/commit/92701f48f9b402ad3dfd0e9cf9693039cd19bf56
