### ISSUE TITLE
Add Scalingo - Privacy Policy

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#308]
New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
https://opentermsarchive.org/en/contribute/service?documentType=Privacy%20Policy&name=Scalingo&selectedCss[]=.title&selectedCss[]=.mx-sm-auto&step=2&url=https%3A%2F%2Fscalingo.com%2Fprivacy-policy&expertMode=true

Or you can see the JSON generated here:
```json
{
  "name": "Scalingo",
  "documents": {
    "Privacy Policy": {
      "fetch": "https://scalingo.com/privacy-policy",
      "select": [
        ".title",
        ".mx-sm-auto"
      ]
    }
  }
}
```

You will need to create the following file in the root of the project: `services/Scalingo.json`

**Comment by clementbiron** [comment]
See https://github.com/ambanum/OpenTermsArchive/commit/92701f48f9b402ad3dfd0e9cf9693039cd19bf56
