### ISSUE TITLE
Add Roblox - undefined

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#310]
New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
https://www.opentermsarchive.org/en/contribute/service?name=Roblox&removedCss[]=.article-relatives&removedCss[]=.article-footer&removedCss[]=.article-title&selectedCss[]=.article&step=2&url=https%3A%2F%2Fen.help.roblox.com%2Fhc%2Fen-us%2Farticles%2F115004647846-Roblox-Terms-of-Use&expertMode=true

Or you can see the JSON generated here:
```json
{
  "name": "Roblox",
  "documents": {
    "???": {
      "fetch": "https://en.help.roblox.com/hc/en-us/articles/115004647846-Roblox-Terms-of-Use",
      "select": [
        ".article"
      ],
      "remove": [
        ".article-relatives",
        ".article-footer",
        ".article-title"
      ]
    }
  }
}
```

You will need to create the following file in the root of the project: `services/Roblox.json`

**Comment by clementbiron** [comment]
See https://github.com/ambanum/OpenTermsArchive/issues/310
