### ISSUE TITLE
Add Roblox - Community Guidelines

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#312]
New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
https://www.opentermsarchive.org/en/contribute/service?documentType=Community%20Guidelines&name=Roblox&removedCss[]=.article-title&removedCss[]=.article-footer&removedCss[]=.article-relatives&selectedCss[]=.article&step=2&url=https%3A%2F%2Fen.help.roblox.com%2Fhc%2Fen-us%2Farticles%2F203313410-Roblox-Community-Rules&expertMode=true

Or you can see the JSON generated here:
```json
{
  "name": "Roblox",
  "documents": {
    "Community Guidelines": {
      "fetch": "https://en.help.roblox.com/hc/en-us/articles/203313410-Roblox-Community-Rules",
      "select": [
        ".article"
      ],
      "remove": [
        ".article-title",
        ".article-footer",
        ".article-relatives"
      ]
    }
  }
}
```

You will need to create the following file in the root of the project: `services/Roblox.json`

**Comment by clementbiron** [comment]
Work in progress https://github.com/ambanum/OpenTermsArchive/issues/316

**Comment by martinratinaud** [comment]
Online: Subscribe here https://opentermsarchive.org/en?documentType=Community%20Guidelines&service=Roblox
