### ISSUE TITLE
Localy Instagram documents  in wrong language

### ISSUE THREAD

**Issue by clementbiron** [ambanum/OpenTermsArchive#395]
Runing localy `npm run start "Instagram"` i get Instagram documents in french.
Online versions are well recorded in english, see https://github.com/ambanum/OpenTermsArchive-versions/tree/master/Instagram

It is confusing not to have the same documents and it can be misleading.

@martinratinaud WDYT ?

**Comment by martinratinaud** [comment]
Got fixed in https://github.com/ambanum/OpenTermsArchive/commit/78f3bedc8b50d9d3581f9d3e6923f6c639e4a136
