### ISSUE TITLE
ASUS Vulnerability Policy selects too much

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#423]
As seen in https://github.com/ambanum/OpenTermsArchive-versions/commit/260915d7c84, this document also stores the security advisories, not only the policy, leading to false positives.

**Comment by clementbiron** [comment]
I think this commit https://github.com/ambanum/OpenTermsArchive/commit/3a8a4ddf6a9fd4e624b34f22459430eceb92e0dc could close this issue, @MattiSG could you take a look ?

**Comment by MattiSG** [comment]
I guess so. We'll see on the next scrape I guess :wink:

Maybe next time, opening a PR rather than committing straight to master would help with a review? 🙂
