### ISSUE TITLE
Centralise document types declaration file

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#656]
- [x] Assess the use of the `translations` entry.
- [x] Remove the `translations` entry. This has already been done in `services-dating`.
- [x] Move back the document types into Open Terms Archive Core.
- [x] Automatically validate the format and contents in CI.

**Comment by MattiSG** [comment]
According to @clementbiron, the `translations` entry is not used currently. The goal was to show a localised version in the contribution UI.

We'll remove it from now, its contents can always be revived from the Git history.

**Comment by Ndpnt** [comment]
Fixed by #736
