### ISSUE TITLE
Support MongoDB as a storage mechanism

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#682]
### Implementation of decision #610

- Abstract away the storage mechanism, currently hardcoded for git.
- Add support for MongoDB through an adapter, with the same resulting API as the git storage backend.
- Add automated tests for MongoDB adapter. Whitebox testing for the implementation with direct access to the database.
- Document that MongoDB should be installed if it is to be used, and how to activate it, in README.
- Document that MongoDB should be installed in CONTRIBUTING.
- Locate both adapters in the `src/storage-adapters` folder.
- Use git as a default storage adapter in config.
- Raise a [`RangeError`](https://nodejs.org/api/errors.html#class-rangeerror) if no known adapter is loaded.

### Notes

- Keep support for git.
- MongoDB is not enabled by default at this stage.
- The git adapter API might change along the way as we discover where to abstract away implementation.

**Comment by Ndpnt** [comment]
Fixed by #722
