### ISSUE TITLE
Move services declarations to separate repository

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#684]
- [x] The `services` folder is moved to a repository `OpenTermsArchive/services-all`.
- [x] Its contents are stored in a `declarations` folder at the root of the repo.
- [x] Move document types declaration into `document-types.json` at the root of the repository.
- [x] Dependencies are declared in a `package.json`.
- [x] The `package.json` has no version and name metadata.
- [x] OTA-Core loads services declarations from a folder given in config.
- [x] Ops loads the services in production.
- [x] Rewrite filters to be independent from OTA-Core API.
- [x] Remove the labels `fix-document` and `add-document`.
- [ ] ~Move validation scripts into the new repository. This implies adding `https://github.com/ambanum/OpenTermsArchive` as a dependency to `OpenTermsArchive/services-all`.~
- [x] Move CI setup to validate service declarations.
- [x] Validate systematically all services in CI, not only those changed.
- [x] Apply a EUPL LICENSE.
- [x] Add a README explaining how this repository is used.
- [x] Move the relevant CONTRIBUTING sections of OTA-Core into Services-All.
- [x] Move the relevant wiki sections of OTA-Core into a `Guidelines.md` file at the root of Services-All.

### Accepted limitations

- OTA-Core is not versioned at this stage. In case of API and document declaration format changes, manual synchronisation between services declaration and Core will have to be handled. Proper semver will be introduced later, for the moment we prefer to move fast without handling versioning.

**Comment by Ndpnt** [comment]
Replaced
- [ ] ~Move validation scripts into the new repository. This implies adding https://github.com/ambanum/OpenTermsArchive as a dependency to OpenTermsArchive/services-all.~

By

- [ ] Expose a validation command from `open-terms-archive` to allow validate service.
