### ISSUE TITLE
Re-enable `chromium` sandbox

### ISSUE THREAD

**Issue by Ndpnt** [ambanum/OpenTermsArchive#699]
When using `FullDomFetcher` to protect the host environment from untrusted web content, re-enable chromium sandbox https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox

**Comment by MattiSG** [comment]
Execute all services on a production server clone and check the process starts properly and if any service is impacted.
