### ISSUE TITLE
Fix `ops` deployment on a phoenix server

### ISSUE THREAD

**Issue by Ndpnt** [ambanum/OpenTermsArchive#700]
There are errors with the installation of `gh` CLI and also with the `dev` config when trying to deploy with `vagrant`.

**Comment by martinratinaud** [comment]
For now we are using `gh` which may be migrated after.

For reference, here was a small doc on how to install `gh`
````
# - name: Install GH -> ⚠️ you need to do "gh auth login" in cgus directory though
#   become: yes
#   ansible.builtin.shell: |
#     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
#     sudo apt-add-repository https://cli.github.com/packages
#     sudo apt update -y
#   tags:
#     - setup
```

I believe that this whole release creation should be in another microservice

**Comment by Ndpnt** [comment]
There are also issues with cloning `snapshots` and `versions` on a phoenix server. It seems there is only one commit after a clean install which prevent refiltering to work properly

**Comment by MattiSG** [comment]
- [ ] Update Debian to Debian 11.
- [ ] Install `gh`.
- [ ] Ensure `snapshots` and `versions` are cloned properly.
- [ ] Ensure Vagrant config works on both @Ndpnt and @martinratinaud setups.

**Comment by martinratinaud** [comment]
I took care of `Gently stop and delete previous pm2 instance with same name` and setup a branch for this whole issue

`fix_ops_phoenix`

@Ndpnt
