### ISSUE TITLE
Notify over email when process stops

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#715]
An email should be sent when the process errors in production. It is currently not 😅

**Comment by martinratinaud** [comment]
It seems like the SMTP password has changed

I wait for @clementbiron to gain access to sendinblue as I can't now (computer must be whitelisted from pariscall-tech.dgp-asd-asc@diplomatie.gouv.fr which I do not have access to)

**Comment by clementbiron** [comment]
New SMTP key created and shared wtih Martin.

**Comment by MattiSG** [comment]
This is marked as “done” in the board but the issue is still open. One or the other should be corrected 😉
How was this tested?

**Comment by martinratinaud** [comment]
I've logged an error in the process on the server and I've received the email accordingly.

Emails are sent to admin@disinfo.beta.gouv.fr.

In the meantime, SIB account address has been changed and with it the SMTP credentials, so I made this PR https://github.com/ambanum/OpenTermsArchive/pull/721

And I added you, @clementbiron and @Ndpnt to the admin@opentermsarchive.org redirection (you should have received an email of error by the way on your ota.org address)
