### ISSUE TITLE
Clean Yuka Terms of Service

### ISSUE THREAD

**Issue by trujilloelsa** [ambanum/OpenTermsArchive#720]
https://github.com/ambanum/OpenTermsArchive-versions/commit/@de56291 
Introduces noise with the date of the last update.

https://github.com/ambanum/OpenTermsArchive-versions/commit/3b1f4fc012a67347624af736b7ed0dc8a639283d

**Comment by MattiSG** [comment]
Fixed via https://github.com/OpenTermsArchive/services-all/pull/237
