### ISSUE TITLE
A user received a notfication of change with a 404 url

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#731]
Here is the email received on Tuesday 14 dec 2021 at 15:28

![Screen Shot 2022-01-11 at 10 32 38](https://user-images.githubusercontent.com/4191809/148892839-ef3d46ec-3d8b-4e42-a73f-81b748bd8a41.png)

The corresponding url is https://github.com/ambanum/OpenTermsArchive-versions/commit/ee54598

This commit does not exist, so we need to investifate what happened

**Comment by Ndpnt** [comment]
This is an email sent by the MongoDB prototype, so versions are not published.

**Comment by martinratinaud** [comment]
@MattiSG can you recontact the user who had this problem and to whom you already answered
