### ISSUE TITLE
Optimise server costs

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#747]
Today we have 4T of classic disks and 300 of SSD disks which makes a total of 184€ per month in addition to the servers (https://www.ovhcloud.com/fr/public-cloud/prices/)

Delete those that are useless and/or reduce the size. The same goes for the servers

**Comment by martinratinaud** [comment]
Here is what we have exactly

- server for historical services (ota-services-all) _b2-30-flex_   **85€**
- experimentation server (Experimentations) _b2-30_ **85€**
- web server (OTA) _b2-30_ **85€**
- volume (ota-mongodb-data) **40€** (1Tb with 450G used)

Total 295€/month

Here what we could have

- server for historical services -> (ota-services-all) _b2-7_   **22€**
- server for UFC Que choisir ->  _b2-7_   **22€**
- web server -> _b2-7_   **22€**
- Experimental server -> _b2-7_ **22€**
- volume (ota-mongodb-data) **30€** (750Gb)

TOTAL 118€/month

@Ndpnt can you please validate this estimation and also let me know if we should get a specific volume for storing data of UFC

Thanks

**Comment by MattiSG** [comment]
_b2-7_ would be just fine, except for volume sizes on Open Terms Archive instances, so that implies creating and attaching new disks. If the database is already 450 GB I suggest to not decrease the volume size.

As seen with @ndpnt, your destination setup seems good.

UFC is already a _b2-7_, should be fine, we'll scale up if needed 🙂

Honestly, this story is very low priority and should not even be in this repository considering it is pure ops 😉 if this is not done by next week I'll close it 🙂

**Comment by martinratinaud** [comment]
I had an iinterview with the person in charge of the servers.
We have a budget @ambnum of 6000€ / year
So we're still fine and I've agreed with him we can stay as is for now.
He specifically asked though that we warn him if we ever create a new instance. WHich I will do.

In case we attach volumes and put mongodb data on it, please note that volume has to be formatted in XFS as it multiply performances by at least 10 (saw this on IMA)

Here is a small doc on how to add such a volume

## Mounting
1. Go on horizon and create a volume (highspeed is a lot better for database data)
2. Attach volume to the corresponding instance from the horizon interface
3. On the machine, check what is your volume by launching `lsblk` (It should be one with no partition)
4. Then use `sudo fdisk /dev/sdX` and answer `n`, `p`, `1`, `w`
5. Format the disk with XFS `sudo mkfs.xfs -f /dev/sdX1`
6. Finally create a folder (usually in `/mnt`) and mount the volume in it: `sudo mount -t auto /dev/sdX1 /mnt/mongodb`

## Unmounting
In case you want to remove a volume, you can 
1. unmount it with `sudo umount /mnt/mongodb`
2. Unattach it from the horizon console
3. Remove the volume from horizon console

This doc should be somewhere else, but i'm not sure where @MattiSG @Ndpnt (as it's more ops than related exactly to OTA)

**Comment by MattiSG** [comment]
Thanks @martinratinaud for this recap and the XFS tip! I think these instructions would be welcome as a new section “Performance optimisation” at the bottom of `ops/README.md` 🙂

**Comment by MattiSG** [comment]
Done in #771.
