### ISSUE TITLE
Deploy continuously all instances

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#755]
- [x] Ensure all instances are on branch `master` of Core.
- [x] Ensure `dating` instance is reachable over SSH.
- [x] Add CD to `dating` instance: https://github.com/OpenTermsArchive/services-dating/pull/38
- [x] Add CD to `france` instance.
- [x] Add CD to `services-all`: done in https://github.com/OpenTermsArchive/services-all/pull/386

**Comment by Ndpnt** [comment]
See https://github.com/OpenTermsArchive/declarations-france/pull/267 and https://github.com/OpenTermsArchive/services-dating/pull/44
