### ISSUE TITLE
Unify email sender

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#758]
Some emails are sent with “OTA Bot” as the sender, some other with “Open Terms Archive”. The sender should be the same everywhere and should be “Open Terms Archive”.

**Comment by martinratinaud** [comment]
In fact we receive emails from 2 senders

- SendInBlue: was previously `OTA Bot` -> changed to `Open Terms Archive`
- Github: is `Open Terms Archive Bot` -> not sure if I should change this in fact

What do you prefer @MattiSG?

**Comment by martinratinaud** [comment]
Also shouldn't we differentiate if it's from services-all, dating, or france

like

Open Terms Archive
Open Terms Archive Dating
Open Terms Archive France

Let me know

**Comment by MattiSG** [comment]
Sounds good, I didn't know this was defined directly in SendInBlue!

As for instance differentiation, I think having one sender should be good enough 🙂 for an end user subscribing to notifications, it is always Open Terms Archive, no matter which instance runs it.
