### ISSUE TITLE
Remove direct link to versions in generated GitHub issues

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#759]
Considering https://github.com/ambanum/OpenTermsArchive/pull/737: `GITHUB_VERSIONS_URL` should be different for the `dating` dataset and for `UFC que choisir`.

This variable was initially setup so that when an issue is created, it is easy to see what has been recorded before thanks to a direct link.

Two options here:

- Add a `GITHUB_REPO_URL` (which should include the branch name like https://github.com/ambanum/OpenTermsArchive-versions/blob/master
- Remove this link from the issue creation

Second option looks like a better fit here because it prevents addition of a variable only for GitHub related issues.

**Comment by martinratinaud** [comment]
@clementbiron, do you use this link when you're fixing a service.
I sometimes do

**Comment by clementbiron** [comment]
Never.

**Comment by martinratinaud** [comment]
Although I find useful, when an error arise, to have a look at what has been already recorded, I remove it as it would add another config variable. But I still think this could have been valuable feedback for debugging.
