### ISSUE TITLE
Create a dedicated france-elections instance

### ISSUE THREAD

**Issue by Ndpnt** [ambanum/OpenTermsArchive#777]
Create instance:

- [x] Provision server
- [x] Set up infrastructure
- [x] Set up all three repositories (`declarations-france-elections`, `snapshots-france-elections`, `versions-france-elections`).
- [x] Add CD
- [x] Generate spreadsheet from RSS feed
- [x] Add doctypes for community guidelines — https://github.com/ambanum/OpenTermsArchive/pull/778

Migrate from France:

- [x] Facebook Terms of Service — https://github.com/OpenTermsArchive/declarations-france-elections/pull/1
- [x] Facebook Privacy Policy — https://github.com/OpenTermsArchive/declarations-france-elections/pull/1
- [x] Twitter Terms of Service — https://github.com/OpenTermsArchive/declarations-france-elections/pull/2
- [x] Twitter Privacy Policy — https://github.com/OpenTermsArchive/declarations-france-elections/pull/2
- [x] Instagram Terms of Service — https://github.com/OpenTermsArchive/declarations-france-elections/pull/3
- [x] Instagram Privacy Policy — https://github.com/OpenTermsArchive/declarations-france-elections/pull/3

Start tracking:

- [x] YouTube Terms of Service — https://github.com/OpenTermsArchive/declarations-france-elections/pull/4
- [x] YouTube Privacy Policy — https://github.com/OpenTermsArchive/declarations-france-elections/pull/4
- [x] LinkedIn Terms of Service — https://github.com/OpenTermsArchive/declarations-france-elections/pull/5
- [x] LinkedIn Privacy Policy — https://github.com/OpenTermsArchive/declarations-france-elections/pull/5

Community Guidelines:

- [x] Facebook Community Guidelines — https://github.com/OpenTermsArchive/declarations-france-elections/pull/8
- [x] Twitter Community Guidelines — https://github.com/OpenTermsArchive/declarations-france-elections/pull/13
- [x] Instagram Community Guidelines — https://github.com/OpenTermsArchive/declarations-france-elections/pull/9
- [x] YouTube Community Guidelines — https://github.com/OpenTermsArchive/declarations-france-elections/pull/10
- [x] LinkedIn Community Guidelines - https://github.com/OpenTermsArchive/declarations-france-elections/pull/37

**Comment by MattiSG** [comment]
Congratulations @Ndpnt @clementbiron, great job, that was fast 💪 👏
