### ISSUE TITLE
Create CGV doctype

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#795]
- writer: paid-for goods or service provider
- audience: end buyer
- subject: warranty, delivery, return of goods or services bought through a moneteray transaction

And migrate all Commercial Terms in France to this new type (https://github.com/OpenTermsArchive/declarations-france/issues/303).

**Comment by MattiSG** [comment]
- “Conditions Générales de Vente” is a [legally-defined](https://www.economie.gouv.fr/dgccrf/Publications/Vie-pratique/Fiches-pratiques/Conditions-generales-de-vente) term in France. It does not seem to exist in this fashion in all other jurisdictions.
- According to Wikipedia, “[Conditions Générales de Vente](https://fr.wikipedia.org/wiki/Conditions_générales_de_vente)” maps to “[Standard form contract](https://en.wikipedia.org/wiki/Standard_form_contract)”, which is not satisfactory: the contents do not match the intent.
- [According to Linguee](https://www.linguee.fr/francais-anglais/search?source=auto&query=Conditions+générales+de+vente), “Conditions Générales de Vente” can be translated as “[General] {Terms|Conditions} of Sale [and Delivery]”.
- Amazon maps its French CGV to “[Conditions of Use & Sale](https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=201909000&ref_=footer_cou)” in the UK and to “[Conditions of Use](https://www.amazon.com/gp/help/customer/display.html?nodeId=201909000&ref_=footer_cou)” in the US.

I am thus hesitating between calling this type “Conditions of Sale” and calling it “Conditions Générales de Vente” and acknowledging its French-specific meaning. This decision could be made by identifying equivalent documents in other jurisdictions.

**Comment by clementbiron** [comment]
I begin to explore equivaldent documents in other jurisdictions:

- BackMarket, United Kingdom, "General Terms and Conditions of Sale": https://www.backmarket.co.uk/terms/sale
- Benneton, USA, "General online sales conditions": https://us.benetton.com/terms/terms.html
- Decathlon, Irlande, "General Terms and Conditions of Sale": https://www.decathlon.ie/content/3-terms-and-conditions-of-use

**Comment by MattiSG** [comment]
Thanks a lot @clementbiron! With this added insight, I am in favour of “General Conditions of Sale”.
