### ISSUE TITLE
FetchDocumentError: Timed out after 30 seconds when trying to fetch

### ISSUE THREAD

**Issue by clementbiron** [ambanum/OpenTermsArchive#799]
With the following declarations 
- esayJet: https://github.com/OpenTermsArchive/declarations-france/commit/086d5f685d2a140e6b33b61bc3826b9ba05c9b6f
- Etihad: https://github.com/OpenTermsArchive/declarations-france/commit/751b1e8810cd96e1200dfc1ac1b7073f7d616e3b
- Iberia: https://github.com/OpenTermsArchive/declarations-france/commit/1fe7142c880a48f2878688c07081158d9706b61d 
- KLM: https://github.com/OpenTermsArchive/declarations-france/commit/33d98cc38e9627af7ba563531af20e6db5a281c7
- Turkish Airlines: https://github.com/OpenTermsArchive/france-declarations/commit/3841b7ca74e41a96977f82e142789983b42bebcc and https://github.com/OpenTermsArchive/france-declarations/commit/323cbbc8bd7907f721aac56765e6a1a0fb136857
- Vueling: https://github.com/OpenTermsArchive/france-declarations/commit/85bcbe3f22cfa7fcc33c4ab2bf8b2ade4953ae68

i get this error with `npm run validate`:

```
FetchDocumentError: Timed out after 30 seconds when trying to fetch '...'
```

and this one with `npm run start`:
```
The document cannot be accessed or its content can not be selected: Timed out after 30 seconds when trying to fetch '...'
```

**Comment by MattiSG** [comment]
This is related to documents and not to Core. Moved to https://github.com/OpenTermsArchive/france-declarations/issues/374.
