### ISSUE TITLE
Add Legal Notices (mentions legales) document type

### ISSUE THREAD

**Issue by mvidonne** [ambanum/OpenTermsArchive#801]
same issue already mentioned here: https://github.com/OpenTermsArchive/services-all/issues/523

**Comment by MattiSG** [comment]
Thanks @mvidonne!

We define document types through a triptych made of:

1. The writer of the document;
2. the targeted audience;
3. the object of the commitment.

We also need to have a unique name for the type. More details can be found in the [document types documentation](https://github.com/OpenTermsArchive/services-all/blob/main/CONTRIBUTING.md#defining-a-new-document-type) 🙂 

In this case, the Mentions Légales are a [requirement under French law](http://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000032400316&cidTexte=LEGITEXT000005789847&dateTexte=20170116), designed to make it possible to contact the hosting provider of any online content for investigation. They are translated literally as Legal Notice, but it seems that the equivalent meaning would be closer to Impressum, which has a [comparable legal mandate](https://fr.wikipedia.org/wiki/Impressum) under German law. While given this specific meaning by German law, this term seems to [exist](https://en.wikipedia.org/wiki/Impressum) with the same meaning in English. [Linguee](https://www.linguee.fr/francais-anglais/search?source=auto&query=mentions+légales) refers translations as “Imprint”, “Impressum”, and “Legal Notices”.

I understand that:

- The `writer` of such document is the `service provider`.
- The `audience` of it is `everyone` (as in “not only its users”).
- The `object` is `identification of the content author and its hosting service for official inquiries`.

Does that description seem to match with the documents you intend to track? 🙂 What are the names of such documents you saw used? Could you please provide us with at least 2 examples of such documents from different providers, ideally in different jurisdictions?

**Comment by mvidonne** [comment]
FreeNow
En français:
https://free-now.com/fr/mentions-legales/
Auf Deutsch.
https://free-now.com/de/impressum/
same company but different texts due to the jurisdiction

https://www.parship.fr/aboutus/
https://www.parship.de/aboutus/
similar text


https://www.adopteunmec.com/legal

**Comment by MattiSG** [comment]
SHEIN calls theirs [“Imprint” in English](https://www.shein.com/imprint-a-746.html) (both international and [UK](https://www.shein.co.uk/imprint-a-746.html)), with a direct translation to “Impression” for their [French version](https://fr.shein.com/imprint-a-746.html) and [“Impressum” in German](https://de.shein.com/imprint-a-746.html), [“Impresión” in Spanish](https://es.shein.com/imprint-a-746.html), [“Imprimir” in Portuguese](https://pt.shein.com/imprint-a-746.html), [“Afdruk” in Dutch](https://nl.shein.com/imprint-a-746.html) (which translates to impression / imprint), [“Impronta” in Italian](https://it.shein.com/imprint-a-746.html).

**Comment by MattiSG** [comment]
Asked the wisdom of the crowd: https://twitter.com/matti_sg/status/1508750286059356164

**Comment by AntoineAugusti** [comment]
"Terms and Conditions" is standard for the federal gov of Canada 🇨🇦 

https://digital.canada.ca/legal/terms/
https://www.canada.ca/en/transparency/terms.html

**Comment by MattiSG** [comment]
Thanks @AntoineAugusti! These Canadian documents seem to be generic Terms of Service indeed, they don't seem to be specifically about the “identification of the content author and its hosting service for official inquiries”. It is totally possible that there is no equivalent in the Canadian jurisdiction of the French Mentions Légales or the German Impressum 🙂

**Comment by MattiSG** [comment]
The results of an informal Twitter survey push for “Legal notice”, but I wonder how biased the question was towards French members.

<img width="583" alt="Screen Shot 2022-04-18 at 10 19 05" src="https://user-images.githubusercontent.com/222463/163779326-957fe788-ed14-479b-ad68-37bd7ec9566f.png">

Based on all the accumulated information, I am in favour of using the English term “Imprint”.
