### ISSUE TITLE
Create repositories templates

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#822]
## Declarations

- README.md
- CONTRIBUTING.md
- LICENSE.md
- declarations/README.md
- package.json
- .github/workflows

## Snapshots

- README.md
- LICENSE.md

## Versions

- README.md
  - Document how to access versions RSS
- CONTRIBUTING.md
- LICENSE.md

## Core

- Update documentation.

**Comment by martinratinaud** [comment]
@MattiSG Please take a look at https://github.com/OpenTermsArchive/template-declarations

It's a first shot with an init script to easily replace/clean up data.

Let me know if you find it useful or if you want me to remove it.

Thanks

**Comment by MattiSG** [comment]
Thanks @martinratinaud!

The template looks good, I'll open a PR with minor improvement suggestions and tasked @Manu1400 with adding a declaration for OpenTermsArchive.org as an example as part of his onboarding / evaluation. I remember we had explored this option in planning and @Ndpnt suggested that getting this service tracked in every instance could be problematic, but I feel it is even more problematic that our template's tests fail because there are no declarations. I suggest that our bootstrap script erases this declaration file 🙂 

For the bootstrap script itself, I see some limitations, listed below. Happy to pair program improvements if you'd like to 🙂

### Two languages

The complexity of having both an implementation in shell and in JS seems high to me. Why not one single language? 🙂

I would prefer shell since we're mostly doing file manipulation. I understand that you found cross-platform limitations with `sed`, but if we stick to POSIX-compliant options and learn from the knowledge documented in [`openfisca-country-template`](https://github.com/openfisca/country-template/blob/master/bootstrap.sh) I'm quite sure we can have something clean working 🙂

Alternatively, if using JS, a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) would seem like a good option to me, instead of manipulating the filesystem.

### CommonJS extension

I don't think we actually need the CommonJS syntax since we are not exporting modules, and I find the `cjs` extension too exotic for a template aimed at entry-level contributors.

### No replacement for maintainer

The `<maintainer>` token is not replaced.

### Token syntax

I am in favour of using a `$` prefix instead of a `<>` wrapping for tokens to be replaced, since this is the variable syntax for both shell and JS template literals.

### Documentation

Instead of redirecting to the GitHub template documentation, I believe it would be useful for reusers to have a very simple step-by-step guide on how to use this template in their work 🙂

**Comment by martinratinaud** [comment]
Nice feedback, thanks

Will implement and let you know!

**Comment by martinratinaud** [comment]
@MattiSG, here is a new version

- removed js script
- used open-fisca way of handling sed <- Thanks for this!
- replace <instance-name> by ${instanceName}
- added a `maintainer` argument to the init script
- made a clearer documentation on how to use this template

I will thus implement the same for versions and snapshots

**Comment by MattiSG** [comment]
Thanks @martinratinaud! This improved version seems much better to me 😊

I wonder just how much it is worth adding the script replacement for versions and templates when it's just one word to edit… if we kept it with just the files, it would be a one-step edition on GitHub. If we use the bootstrap shell script way, one would need to clone the repository, run the script, and push again. WDYT?

## Left to do for snapshots and versions

- Add license files.
- Mark repositories as templates.

## Suggestions for declarations template 

- `README-original.md` → `README.template.md`?
- Documentation for secrets that are used in the GitHub Actions workflow.
- Deactivate the `deploy` workflow when run on the template itself, either by renaming the workflow file with the script, or by adding a condition on the repo name (I couldn't quickly find if that name is exposed in an environment variable or not), or maybe by using a different branch name than `main` in the template (like `template/main`), but this last option would need to check if the branch names are also forwarded to the newly-generated repository, in which case it would not work.

## Notes for a future step in industrialisation

- [This solution](https://stefanbuck.com/blog/repository-templates-meets-github-actions) relying on cookiecutter and GitHub Actions seems way more elegant than a script that needs to be run locally. Since there is an API call in it, we might just as well create all three repositories in a single job.
- We would benefit strongly from setting up labels automatically in the `declarations` repository, for example based on [what we consolidate in `france`](https://github.com/OpenTermsArchive/france-declarations/labels). Labels are not forwarded from the template, so I believe this should be done through the GitHub API.

**Comment by martinratinaud** [comment]
Hi @MattiSG thanks

- [X] Add license files
- [X] Mark repositories as templates 
- [X] Reviewed directory structure to make it more obvious to use init script AND to prevent deploy workflow https://github.com/OpenTermsArchive/template-declarations/pull/2
- [X] documented secrets https://github.com/OpenTermsArchive/template-declarations/pull/3
- [ ] if new directory structure is fine with you, do it on `versions` and `snapshots`


The `cookiecutter` way to handle things looks very promising indeed and should be investigated further.
I believe we should create the labels directly indeed also, for this we can
- use https://github.com/drevops/github-labels/blob/master/create-github-labels.sh
- add doc for setting up the correct

**Comment by MattiSG** [comment]
https://github.com/OpenTermsArchive/template-versions seems to have `master` as its main branch while the two others have `main`, let's unify to `main` 🙂

**Comment by martinratinaud** [comment]
Good catch, I 'm not sure how this happened though but changed it

**Comment by MattiSG** [comment]
Yeah I was really surprised that one randomly had this different branch name!

**Comment by martinratinaud** [comment]
> Here is the list of corresponding changes made
> 
> * [x]  https://github.com/OpenTermsArchive/template-declarations
> * [ ]  https://github.com/OpenTermsArchive/template-snapshots [OpenTermsArchive/template-snapshots#1](https://github.com/OpenTermsArchive/template-snapshots/pull/1)
> * [ ]  https://github.com/OpenTermsArchive/template-versions [OpenTermsArchive/template-versions#1](https://github.com/OpenTermsArchive/template-versions/pull/1)
> * [ ]  #826

@MattiSG only need this left before closing this

**Comment by MattiSG** [comment]
All done, thanks @martinratinaud! 🙂
