### ISSUE TITLE
wrong link: recap of available RSS feeds

### ISSUE THREAD

**Issue by mvidonne** [ambanum/OpenTermsArchive#831]
@MattiSG  The link to monitor all the document changes of a service is not correct (master instead of main)
Please modify as follow:
https://github.com/OpenTermsArchive/contrib-versions/commits/main/$serviceId.atom.

ex
https://github.com/OpenTermsArchive/versions-france/commits/main/Uber.atom

**Comment by MattiSG** [comment]
Thanks @mvidonne! Unfortunately the example is given for `contrib-versions` which still uses `master` as its main branch… we'll definitely update the name of branch in the README, but for that we also need to update the published branch in `contrib-versions`. This should be done in any case, thanks for pointing it out! 👍

**Comment by MattiSG** [comment]
Should be unblocked by https://github.com/OpenTermsArchive/contrib-versions/issues/10

**Comment by martinratinaud** [comment]
I tested all atom links listed in the README and they now work
