### ISSUE TITLE
Lint declaration files

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#833]
Declaration validation does not lint files.

### What happened

I tried to validate with `npm run validate Example` this misindented declaration:

```json
{
"name": "Example",
    "documents": {
    "Terms of Service":
    {
    "fetch": "https://domain.example/tos",
    "select": "body"
  }
}
}
```

And I got no error.

### What I expected

An error in the style of:

```
Indentation is incorrect: expected 2 spaces on line 2
```

**Comment by martinratinaud** [comment]
After some investigations and a lot of testing, here is what I found

- Could not make https://github.com/azeemba/eslint-plugin-json#readme work as it does not have indentation rules
- Tried `jsonlint` with no success as detail of errors were not sufficient
- Same with `json-lint`
- Considered using `prettier`but did not want to ad another (not-eslint) dependency
- Found https://github.com/kuceb/eslint-plugin-json-format#readme which works as expected

Here is an example of what it looks like when launching `npm run test Aigle` from `france-declarations`
<img width="1266" alt="Screenshot 2022-05-05 at 14 46 00" src="https://user-images.githubusercontent.com/4191809/166908385-3b7f6a77-6c66-42d6-a482-a46dd32ebd5c.png">

I will try now to add an autofix feature.
My first idea is to use it with 

`npm run test Aigle --fix`

**Comment by MattiSG** [comment]
Thanks @martinratinaud!

The error message depicted above does not seem very clear to me 😕

Please prioritise clear error messages over any auto fix feature 🙂

**Comment by MattiSG** [comment]
The goal here is simply to prevent misformated files from being put in production. Let's not increase too much the API scope.

**Comment by martinratinaud** [comment]
@MattiSG I'm not sure to understand why you think this is not clear enough

For example a normal eslint error is displayed like this
<img width="583" alt="Screenshot 2022-05-05 at 15 10 51" src="https://user-images.githubusercontent.com/4191809/166911910-473e50aa-4988-4738-8445-dfdca7c36dc9.png">

In My Opinion, the current error states
- the path of the file concerned
- the line(s) concerned
- the unexpected character on this particular line

Considering the above, can you please elaborate what you find not clear enough?

In the meantime, possible solutions to make it clearer:
- I'm not sure how to get the coloring with chai but I can look into that.
- I can also display the expecting json to copy paste in the file
- if the above is good enough, then no auto fixing is needed

**Comment by martinratinaud** [comment]
Note also that 
- this is only for json files, but we should also validate filters.js and history files.
- all declaration folders will need to be fixed, commited and pushed with a command like `npx eslint ../contrib-declarations/declarations/*.json -c .eslintrc.yaml --fix`

**Comment by martinratinaud** [comment]
Here it is with a more convenient format

<img width="900" alt="Screenshot 2022-05-05 at 15 42 06" src="https://user-images.githubusercontent.com/4191809/166916239-5c2d2a69-eb0f-4664-bcb9-4e49dd740a71.png">

**Comment by martinratinaud** [comment]
In fact I actually added a new commit to not only lint the declaration files but also the filters and history files.
![Screenshot 2022-05-05 at 16 18 33](https://user-images.githubusercontent.com/4191809/166921441-7d9eefb5-b590-4944-921e-112a078a3369.png)

It looks now a lot more concise IMO and Js files won't be a mess anymore also

**Comment by martinratinaud** [comment]
Main PR is almost ready and those for declarations folders too

- [ ] OTA core https://github.com/ambanum/OpenTermsArchive/pull/841
- [ ] france-declarations https://github.com/OpenTermsArchive/france-declarations/pull/409
- [ ] contrib-declarations https://github.com/OpenTermsArchive/contrib-declarations/pull/565
- [ ] dating-declarations https://github.com/OpenTermsArchive/dating-declarations/pull/92
- [ ] france-elections-declarations https://github.com/OpenTermsArchive/france-elections-declarations/pull/111
- [ ] template-declarations https://github.com/OpenTermsArchive/template-declarations/pull/7
