### ISSUE TITLE
Automatically create GitHub issues creation labels

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#837]
The automated GitHub issue creation mechanism relies on tags being set on the automated issues. These tags should be created automatically as they lead otherwise to duplicated issues each time we create a new instance.

The default tag value should be changed to `bot-report` since `update` is duplicate information with the name of the issue.

**Comment by martinratinaud** [comment]
@Ndpnt here is the PR https://github.com/ambanum/OpenTermsArchive/issues/837

I currently create the label at instantiation of the Tracker. As it is in a constructor, promise is not awaited (I believe this is not a problem as first error creation should occur way after this promise is resolved)

That leads to the following question:
What should we do if label creation fails ? There is today an error displayed in the logs but I'm wondering if it's sufficient.

Handling this would make the code slightly more complicated, here are 2 solutions:
1. keep track of the created label id and, if label creation did not work, retry within the `onVersionRecorded`, `onVersionNotChanged` and `onInaccessibleContent`. This would lead to more resilience as the odds of having a fail twice are very thin.
2. always create label in `onVersionRecorded`, `onVersionNotChanged` and `onInaccessibleContent` (Not recommended as we would have a lot of unnecessary calls to the API)

I think leaving it this way is fine as the odds of having an error from Github at setup are very thin and the worst that can happen is some duplicate issues. 

Please let me know what you think are have a chat about it

**Comment by martinratinaud** [comment]
Here are the actions to take

- [ ] Deploy on all instances
- [ ] Update tag on PGA (add `bot-report` tag to all issues with `update` tag and remove `update` tag)
- [ ] Rename tag on contrib
- [ ] Rename tag on france
- [ ] Rename tag on france-elections
- [ ] Rename tag on dating
- [ ] Create `add` tag automatically on contribution tool
