### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#856]
The default in all other repository is progressively switching to `main`, rename out of consistency.

- [x] Update ops.
- [ ] Update GitHub workflows.
- [x] Update doc.
- [x] Update README & CONTRIBUTING.

Steps:

- [x] Create `main` on `master`.
- [x] Create PR towards `main`.
- [x] Get PR approved.
- [x] Update all instances (and Contribution Tool too if it depends on `#master`).
- [x] Switch main branch in GitHub settings to `main`.
- [ ] Merge PR.
- [ ] Check that all workflows were run properly and that the deployments were successful.
- [ ] Switch destination branch for all open PRs to `main`.
- [ ] Remove `master` branch.

**Comment by martinratinaud** [comment]
Point of attention
- OPS: no need to update, it takes by default the main (default) branch

Associated PRs
- Core: https://github.com/ambanum/OpenTermsArchive/pull/858
- Dating: https://github.com/OpenTermsArchive/dating-declarations/pull/93
- France: https://github.com/OpenTermsArchive/france-declarations/pull/414
- France elections: https://github.com/OpenTermsArchive/france-elections-declarations/pull/137
- Contrib: https://github.com/OpenTermsArchive/contrib-declarations/pull/570
- Template: https://github.com/OpenTermsArchive/template-declarations/pull/8
