### ISSUE TITLE
Do not consider DNS lookup errors as FetchDocumentError

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#857]
A large number of declarations in France failed [because of `EAI_AGAIN`](https://github.com/OpenTermsArchive/france-declarations/issues?q=is%3Aissue+EAI_AGAIN) errors. These seem to be linked to [DNS lookup](https://stackoverflow.com/questions/40182121/whats-the-cause-of-the-error-getaddrinfo-eai-again) failing. These should not be considered as document fetch failure but like network errors instead, crashing the app and generating an email to the administrators.

**Comment by martinratinaud** [comment]
I couldn't find a way to mock a DNS error in the test though.
If you know how to, I'm interested

**Comment by Ndpnt** [comment]
Fixed by #871
