### ISSUE TITLE
Include resulting documents in declarations pull requests

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#888]
In a PR of a declaration edition or addition, a bot should publish the resulting version, in order to ease the reviewer's job.

- Resulting version.
- Resulting snapshot.

### Ideas

- Use GitHub CI's Artefact generation.
- Display as GitHub Checks.

**Comment by martinratinaud** [comment]
Well after some digging, I managed to
- add new tooling in OpenTermsArchive to be able to launch OTA command straight from the declarations folder and get save snapshots and versions locally in the `data` folder (See [PR](https://github.com/ambanum/OpenTermsArchive/pull/895/files))
- Generate and upload artifacts on each build run [See PR](https://github.com/OpenTermsArchive/sandbox-declarations/pull/14)

The whole folder is thus available for download a  zip file, which is not really convenient.

I tried to upload [each file one by one](https://github.com/OpenTermsArchive/sandbox-declarations/actions/runs/2711252446) but it does not help seeing the files directly in the browser unfortunately, it just creates another zip file to be downloaded. I thus rollbacked to have only one zip file to download.

I couldn't find a way to use Github checks. And the upload_artifacts makes it very difficult to retrieve the actual artifacts url.
When this feature is available, it could be fairly easy to add a comment to the PR with a direct link to the artifacts to be downloaded but for now it's not doable easily (or at least I could not find how)

**Comment by martinratinaud** [comment]
@MattiSG maybe if you have some time to review these PRs so that I can merge it next week.

**Comment by MattiSG** [comment]
Following https://github.com/OpenTermsArchive/contribution-tool/pull/94 and https://github.com/OpenTermsArchive/contribution-tool/pull/132, this is now easily doable through the contribution tool links and a dedicated one-click solution is not relevant anymore 🙂
